// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArmNext(arg1, arg2) {
  return window['go']['main']['App']['ArmNext'](arg1, arg2);
}

export function ListRenderers() {
  return window['go']['main']['App']['ListRenderers']();
}

export function LoadProgram(arg1) {
  return window['go']['main']['App']['LoadProgram'](arg1);
}

export function RunTest(arg1) {
  return window['go']['main']['App']['RunTest'](arg1);
}

export function SeqCmd(arg1) {
  return window['go']['main']['App']['SeqCmd'](arg1);
}

export function SetBool(arg1, arg2) {
  return window['go']['main']['App']['SetBool'](arg1, arg2);
}

export function SetParam(arg1, arg2) {
  return window['go']['main']['App']['SetParam'](arg1, arg2);
}

export function SetRenderer(arg1, arg2) {
  return window['go']['main']['App']['SetRenderer'](arg1, arg2);
}
