// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArmNext(arg1:string,arg2:string):Promise<void>;

export function ListRenderers():Promise<Array<string>>;

export function LoadProgram(arg1:string):Promise<void>;

export function RunTest(arg1:string):Promise<string>;

export function SeqCmd(arg1:string):Promise<void>;

export function SetBool(arg1:string,arg2:boolean):Promise<void>;

export function SetParam(arg1:string,arg2:number):Promise<void>;

export function SetRenderer(arg1:string,arg2:string):Promise<void>;
